### ISSUE TITLE
Request for credit referenced project

### ISSUE THREAD

**Issue by SpriteOvO** [piz-ewing/sigmatch#1]
Hi, first of all, thank you for creating this project to contribute to the open source community! 👍

I just found this Rust crate by accident. I was interested in this project because I had a C++ project with the same name and the same functionality - https://github.com/SpriteOvO/sigmatch, and I saw that you wrote this in the README

> It's a basic version migrated from another C++ project of mine, with more features coming soon!

I'm not sure if this project referenced my code. If so, please don't be shy to credit the URL of the project you referenced in the README, and  I'd appreciate it if you would do so. If this is all a coincidence, then please forgive me for my incorrect guess.

But thanks anyway for all your hard work developing this project.

Best regards.

**Comment by piz-ewing** [comment]
`sigmatch` 是一个不错的名字，😄

可以确信，除了名字，它们的设计思路和目标完全不一样。这是从**我的**另一个c++项目迁移而来。

首先可以确定 [SpriteOvO/sigmatch](https://github.com/SpriteOvO/sigmatch) 当前 `Features` 的所有内容皆不在本项目的考虑范围(*跨进程搜索，多线程搜索，又或者是特征通配及多目标*)。

本项目的重点在于下列内容：

1. 更关注性能和稳定性，运行时性能是首要目标。例如本项目对页属性相关处理的算法是精心设计并针对性能调优过。
2. 更关注特征码与逆向工程工具 (IDA Pro, x96dbg....)的结合。
3. 目前只关注 windows 平台，主要应用场景在于注入目标进程后匹配指定特征。

硬要追溯起源的话，可以参考 [bCompare](https://github.com/piz-ewing/UeDePak/blob/77d2a686a0ac432b5abb20d6d1ccc2775959d6f7/UeDePak/Util.cpp#L16)，大约十年前就流行于互联网的一段特征码匹配算法。

它位于本项目 [compare](https://github.com/piz-ewing/sigmatch/blob/dbce0f92f76d29cf7b47e4b372cd4ef98a857c14/src/lib.rs#L497) 处，作为核心匹配算法存在。

[SpriteOvO/sigmatch](https://github.com/SpriteOvO/sigmatch) 同样是一个很优秀，整洁的项目，算法和设计思路应该更接近 [BlackBone](https://github.com/karliky/Blackbone/blob/3b087d1f53ea6577f0b6945dd08bc6ba85b10b27/src/BlackBone/Patterns/PatternSearch.cpp#L215) 。

最后感谢你们对开源社区的贡献✌。希望以上说明能解答你的困惑。

**Comment by SpriteOvO** [comment]
Thanks for your clarification. I apologize for my incorrect guess.
